# Define UI for data upload app ----
library("shiny", quietly = TRUE)

name_space <- shiny::NS("lfq")
# name_space <- function(id) { id }

mySvg <- function(id, text) {
  downloadButton(id, text, class = "w-25 mx-auto")
}

ACTION_CLASS <- "w-50 mx-auto"

ICON_ACTION <- icon("person-running")

quick_start_page <- function() {
  bslib::card(
    class = "border-danger",
    bslib::card_header(class = "bg-danger text-light", "Getting Started"),
    h3(tags$b(span("Quick Start", style = "text-decoration:underline"))),
    tags$ul(
      tags$li("Upload your ", tags$b("proteinGroups.txt "), "generated by MaxQuant."),
      tags$li("Upload your ", tags$b(" experimental design "), "table. "),
      tags$li(tags$b("Optional: "), "Adjust the p-value cut-off, the log2 fold change cut-off,
                                the imputation type, FDR correction method and/or number of clusters in heatmap
                                in the", tags$b("Advanced Options")),
      tags$li("Press ", tags$b("'Start Analysis' ")),
      tags$li(tags$b("Note: "), " The experimental design file is not the", tags$b("'mqpar.xml' "), "file
                        from MaxQuant.")
    ),
    br(),
    HTML('<center><img src="/static/img/LFQ_analyst.svg" width="500px"></center>')
  )
}

# dataset
# downloadData
# significantBox
# downloadReport
top_row <- function() {
  bslib::layout_columns(
    col_widths = c(4, 5, 3),
    bslib::card(
      bslib::layout_columns(
        selectizeInput(
          name_space("dataset"),
          "Choose a dataset to save",
          choice = c(
            "Results", "Original_matrix",
            "Imputed_matrix",
            "Full_dataset"
          ),
          options = list(dropdownParent = "body")
        ),
        downloadButton(name_space("downloadData"), "Save", class = "mt-4 p-2")
      )
    ),
    uiOutput(name_space("significantBox")),
    bslib::card(
      downloadButton(name_space("downloadReport"), "Download Report", class = "mt-3 p-2")
    )
  )
}

# contents
# original
results_table <- function() {
  bslib::card(
    class = "border-success",
    bslib::card_header(class = "bg-success", "LFQ Results Table"),
    DT::dataTableOutput(name_space("contents")),
    actionButton(name_space("original"), "Refresh Table", icon = ICON_ACTION, class = ACTION_CLASS)
  )
}
# volcano_cntrst_placeholder
# fontsize
# check_names
# p_adj
# volcano_plot protein_brush protein_click
# downloadVolcano
# resetPlot
# heatmap
# cluster_number
# downloadCluster
# download_hm_svg
# protein_plot_type
# protein_plot
# downloadProtein
results_plots <- function() {
  bslib::navset_card_underline(
    title = "Result Plots",
    bslib::nav_panel(
      title = "Volcano plot",
      bslib::layout_columns(
        # col_widths = c(4, 4, 4),
        # style = htmltools::css(grid_template_columns = "1fr 1fr 1fr"),
        uiOutput(name_space("volcano_cntrst_placeholder")),
        numericInput(name_space("fontsize"),
          "Font size",
          min = 0, max = 8, value = 4
        ),
        bslib::card(
          checkboxInput(name_space("check_names"),
            "Display names",
            value = FALSE
          ),
          checkboxInput(name_space("p_adj"),
            "Adjusted p values",
            value = FALSE
          )
        )
      ),
      tags$p("Select protein from LFQ Results Table to highlight on the plot OR
                                                  drag the mouse on plot to show expression of proteins in Table"),
      bslib::card(
        plotOutput(name_space("volcano_plot"),
          height = 600,
          # hover = "protein_hover"),
          # ),
          # click = "protein_click"),
          brush = "protein_brush",
          click = "protein_click"
        ),
        bslib::layout_columns(
          # style = htmltools::css(grid_template_columns = "1fr 1fr"),
          downloadButton(name_space("downloadVolcano"), "Save Highlighted Plot"),
          actionButton(name_space("resetPlot"), "Clear Selection", icon = ICON_ACTION)
        )
      )
    ),
    bslib::nav_panel(
      title = "Heatmap",
      plotOutput(name_space("heatmap_plot"), height = 600),
      bslib::layout_columns(
        # style = htmltools::css(grid_template_columns = "1fr 1fr 1fr"),
        numericInput(name_space("cluster_number"),
          "Cluster to download",
          min = 1, max = 6, value = 1
        ),
        downloadButton(name_space("downloadCluster"), "Save Cluster", class = "mt-3"),
        downloadButton(name_space("download_hm_svg"), "Save svg", class = "mt-3"),
      )
      # # align save button
      # tags$style(type = "text/css", "#downloadCluster {margin-top: 25px;}"),
      # tags$style(type = "text/css", "#download_hm_svg {margin-top: 25px;}")
    ),
    bslib::nav_panel(
      title = "Protein Plot",
      bslib::card(
        radioButtons(name_space("protein_plot_type"),
          "Plot type",
          choices = c(
            "Box Plot" = "boxplot",
            "Violin Plot" = "violin",
            "Interaction Plot" = "interaction",
            "Intensity Plot" = "dot"
          ),
          selected = "boxplot",
          inline = TRUE
        )
      ),
      tags$p("Select one or more rows from LFQ Results Table to plot individual
                                                  protein intesities across conditions and replicates"),
      bslib::card(
        plotOutput(name_space("protein_plot")),
        downloadButton(name_space("downloadProtein"), "Download Plot")
      )
    )
  )
}

# pca_plot
# download_pca_svg
# sample_corr_plot
# download_corr_svg
# sample_cvs_plot
# download_cvs_svg
# numbers_plot
# download_num_svg
# coverage_plot
# download_cov_svg
# normalization_plot
# download_norm_svg
# missval_plot
# download_missval_svg
# imputation_plot
# download_imp_svg
qc_plots <- function() {
  bslib::navset_card_underline(
    # title = "QC Plots",
    bslib::nav_panel(
      title = "PCA Plot",
      plotOutput(name_space("pca_plot"), height = 600),
      mySvg(name_space("download_pca_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Sample Correlation",
      plotOutput(name_space("sample_corr_plot"), height = 600),
      mySvg(name_space("download_corr_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Sample CVs",
      plotOutput(name_space("sample_cvs_plot"), height = 600),
      mySvg(name_space("download_cvs_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Protein Numbers",
      plotOutput(name_space("numbers_plot"), height = 600),
      mySvg(name_space("download_num_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Sample coverage",
      plotOutput(name_space("coverage_plot"), height = 600),
      mySvg(name_space("download_cov_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Normalization",
      plotOutput(name_space("normalization_plot"), height = 600),
      mySvg(name_space("download_norm_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Missing values - Heatmap",
      plotOutput(name_space("missval_plot"), height = 600),
      mySvg(name_space("download_missval_svg"), "Save svg")
    ),
    bslib::nav_panel(
      title = "Imputation",
      plotOutput(name_space("imputation_plot"), height = 600),
      mySvg(name_space("download_imp_svg"), "Save svg")
    ),
    bslib::nav_spacer(),
    bslib::nav_item("QC Plots")
  )
}

# contrast_placeholder
# go_database
# go_analysis
# spinner_go
# downloadGO
# contrast_1_placeholder
# pathway_database
# pathway_analysis
# spinner_pa
# downloadPA
enrichment_box <- function() {
  bslib::navset_card_underline(
    title = "Enrichment",
    bslib::nav_panel(
      title = "Gene Ontology",
      bslib::layout_columns(
        uiOutput(name_space("contrast_placeholder")),
        selectizeInput(
          name_space("go_database"), "GO database:",
          choices = c(
            "Molecular Function" = "GO_Molecular_Function_2021",
            "Cellular Component" = "GO_Cellular_Component_2021",
            "Biological Process" = "GO_Biological_Process_2021"
          ),
          options = list(dropdownParent = "body")
        ),
        actionButton(
          name_space("go_analysis"), "Run Enrichment",
          class = "mt-4 p-2",
          icon = ICON_ACTION
        )
      ),
      bslib::card(uiOutput(name_space("spinner_go"))),
      downloadButton(name_space("downloadGO"), "Download Table", class = "w-50 mx-auto")
    ),
    bslib::nav_panel(
      title = "Pathway enrichment",
      bslib::layout_columns(
        uiOutput(name_space("contrast_1_placeholder")),
        selectizeInput(
          name_space("pathway_database"), "Pathway database:",
          choices = c(
            "KEGG" = "KEGG_2021_Human",
            "Reactome" = "Reactome_2022"
          ),
          options = list(dropdownParent = "body")
        ),
        actionButton(
          name_space("pathway_analysis"), "Run Enrichment",
          class = "mt-4 p-2",
          icon = ICON_ACTION
        ),
      ),
      bslib::card(uiOutput(name_space("spinner_pa")), height = 400),
      downloadButton(name_space("downloadPA"), "Download Table")
    )
  )
}


# quickstart_info
# analysis_id
analysis_tab <- function() {
  tagList(
    div(
      id = name_space("quickstart_info"), quick_start_page()
    ),
    shinyjs::hidden(
      div(
        id = name_space("analysis_id"),
        top_row(),
        bslib::layout_columns(
          results_table(),
          results_plots()
        ),
        bslib::layout_columns(
          qc_plots(),
          enrichment_box()
        )
      )
    )
  )
}


# maxquant_file
# exp_design_file
# analyze
# p_value
# log_fold_change
# paired
# imputation
# fdr_correction
# single_peptide
# k_number
sidebar_panel <- function() {
  bslib::layout_sidebar(
    title = "Analysis",
    sidebar = bslib::sidebar(
      width = "20rem",
      bslib::accordion(
        bslib::accordion_panel(
          title = "Analysis", icon = icon("flask"),
          open = TRUE,
          fileInput(name_space("maxquant_file"),
            "Upload MaxQuant ProteinGroups.txt",
            accept = c(
              "text/csv",
              "text/comma-separated-values,text/plain",
              ".csv"
            )
          ),
          fileInput(name_space("exp_design_file"),
            "Upload Experimental Design Matrix",
            accept = c(
              "text/csv",
              "text/comma-separated-values,text/plain",
              ".csv"
            )
          ),
          tags$hr(),
          actionButton(name_space("analyze"), "Start Analysis", icon = ICON_ACTION)
        ),
        bslib::accordion_panel(
          title = "Advanced Options",
          icon = icon("cogs"),
          numericInput(name_space("p_value"),
            "Adjusted p-value cutoff",
            min = 0.0001, max = 0.1, value = 0.05
          ),
          numericInput(name_space("log_fold_change"),
            "Log2 fold change cutoff",
            min = 0, max = 10, value = 1
          ),
          checkboxInput(
            name_space("paired"),
            "Paired test", FALSE
          ),
          radioButtons(name_space("imputation"),
            "Imputation type",
            choices = c("Perseus-type" = "man", MsCoreUtils::imputeMethods())[1:9],
            selected = "man"
          ),
          radioButtons(name_space("fdr_correction"),
            "Type of FDR correction",
            choices = c(
              "Benjamini Hochberg" = "BH",
              "t-statistics-based" = "fdrtool"
            ), selected = "BH"
          ),
          checkboxInput(
            name_space("single_peptide"),
            "Include single peptide identifications", FALSE
          ),
          numericInput(name_space("k_number"),
            "Number of clusters in heatmap",
            min = 1, max = 20, value = 6
          )
        )
      )
    ),
    analysis_tab()
  )
}


link_LFQ <- tags$a(icon("chart-line"), "LFQ-Analyst",
  href = "https://bioinformatics.erc.monash.edu/apps/LFQ-Analyst/",
  target = "_blank"
)

ui <- shinyUI({
  bslib::page_navbar(
    title = tags$span("LFQ"),
    theme = bslib::bs_theme(version = 5, font_scale = .7),
    navbar_options = bslib::navbar_options(
      bg = "#0062cc"
    ),
    id = "page",
    window_title = "LFQ",
    fillable = FALSE,
    header = tagList(
      shinydisconnect::disconnectMessage(),
      tags$head(
        # tags$link(rel = "icon", href = ICON),
        # tags$link(rel = "stylesheet", type = "text/css", href = "/static/css/custom.css?v=1.5"),
        tags$style(HTML("
          :root {
            --bslib-spacer: .5rem;
          }

          .card, .well {
            --bs-card-border-radius: 0px;
            --bs-card-inner-border-radius: 0px;
          }

        ")),
        shinyjs::useShinyjs() # imp to use shinyjs functions
      )
    ),
    bslib::nav_panel(
      title = "LFQ", value = "lfq", icon = icon("list"),
      sidebar_panel()
    ),
    bslib::nav_spacer(),
    bslib::nav_item(link_LFQ)
    # footer = tagList(
    #   tags$p("Supported by: Monash Proteomics and Metabolomics Platform & Monash Bioinformatics Platform,
    #           Monash University"),
    #   #shiny.info::version(position = "bottom right")
    # )
  )
})
